# Generated by Django 5.1.7 on 2025-03-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='inventario',
            new_name='venta',
        ),
    ]
