# Generated by Django 5.1.7 on 2025-03-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_transaccion_detalletransaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletransaccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
