# Generated by Django 5.1.7 on 2025-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_nombre_producto_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
